<?php

namespace slinstj\assets\optimizer\tests;

use slinstj\assets\optimizer\AssetsOptimizerView;
use Yii;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-30 at 17:45:03.
 */
class AssetsOptimizerViewTest extends TestCase
{

    /**
     * @var AssetsOptimizerView
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->mockWebApplication();
        $this->object = new AssetsOptimizerView;
    }

    /**
     * @covers slinstj\assets\optimizer\AssetsOptimizerView::init
     * @todo   Implement testInit().
     */
    public function testInit()
    {
        $this->assertInstanceOf('\slinstj\assets\optimizer\AssetsOptimizerView', Yii::$app->view);
        $this->assertInstanceOf('\slinstj\assets\optimizer\AssetsOptimizerView', $this->object);
    }

    /**
     * @covers slinstj\assets\optimizer\AssetsOptimizerView::endPage
     * @todo   Implement testEndPage().
     */
    public function testEndPage()
    {
        $r = $this->object->renderFile(__DIR__ . '/testing-view.php');
        $this->assertTrue($r);
    }

}
